# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
- develop
- feature/API_tests

pool: local

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: DeleteFiles@1
  displayName: 'Cleanup AllureResult'
  inputs:
    contents: |
      .\AQA_MTS_Graduate_work\Graduate_work\bin\Debug\net8.0\allure-results

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './AQA_MTS_Graduate_work/Graduate_work/Graduate_work.csproj'

- task: PublishAllureReport@1
  displayName: Publish Report
  condition: always()
  inputs:
    allureVersion: 2.27.0
    testResultsDir: .\AQA_MTS_Graduate_work\Graduate_work\bin\Debug\net8.0\allure-results
